# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: PyLint the codebase

on:
  push:
    branches:
    - main

jobs:
  run_pylint:
    runs-on: ubuntu-latest
    name: Execute pylint
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Python Pylint GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc --recursive=y ./
